spring:
  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.48.129/sell?useUnicode=true&CharacterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true